'use client'

import "./globals.css";

import { ThemeProvider, CssBaseline } from "@mui/material";
import { createTheme } from '@mui/material/styles';

const MuiTheme = createTheme({
  palette: {
    mode: 'light',
    primary: {
      main: '#2a609d',
    }
  }
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-Br">
      <head>
        <title>Create Next App</title>

        <meta name="description" content="Generated by create next app" />

        <link rel="icon" href="/favicon.ico" />
      </head>

      <ThemeProvider theme={MuiTheme}>
        <CssBaseline />

        <body>
          {children}
        </body>
      </ThemeProvider>
    </html>
  )
}
