'use client'

import "./globals.css";
import 'slick-carousel/slick/slick.css';
import 'slick-carousel/slick/slick-theme.css';

import { ThemeProvider, CssBaseline } from "@mui/material";
import { createTheme } from '@mui/material/styles';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'

const queryClient = new QueryClient()

const MuiTheme = createTheme({
  palette: {
    mode: 'light',
    primary: {
      main: '#2a609d',
    }
  }
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-Br">
      <head>
        <title>Create Next App</title>

        <meta name="description" content="Generated by create next app" />

        <link rel="icon" href="/favicon.ico" />
      </head>

      <QueryClientProvider client={queryClient}>
        <ThemeProvider theme={MuiTheme}>
          <CssBaseline />

          <body>
            {children}
          </body>
        </ThemeProvider>
      </QueryClientProvider>
    </html>
  )
}
